const ADJECTIVES = [
  'ABLE','ACID','AGED','AGILE','ALERT','ANCIENT','ARCTIC','ARID','ARMED','ASHEN',
  'BARE','BARREN','BITTER','BLACK','BLEAK','BLIND','BOLD','BRAVE','BRIGHT','BROKEN',
  'BRONZE','BURNT','CALM','CHARRED','CLEAR','COBALT','COLD','COVERT','CRISP','CRIMSON',
  'CROOKED','DARK','DEAD','DEEP','DENSE','DIM','DIRE','DISTANT','DULL','DUSTY',
  'EAGER','EMPTY','FALLEN','FIERCE','FIXED','FLAT','FLEET','FOUL','FROZEN','GAUNT',
  'GRIM','GRUFF','HARD','HARSH','HEAVY','HIDDEN','HOLLOW','HOWLING','HUNGRY','ICED',
  'IDLE','IRON','JAGGED','KEEN','LEADEN','LEAN','LIVID','LONE','LOST','LOUD',
  'MURKY','MUTED','NARROW','OBSIDIAN','ONYX','PALE','PHANTOM','QUIET','RAGGED','RAPID',
  'RAW','RIGID','ROUGH','RUGGED','RUST','SALT','SCARLET','SHARP','SILENT','SILVER',
  'SLATE','SLOW','SMOKY','SOLEMN','STARK','STEEL','STERN','STIFF','STILL','STOIC',
  'STONE','STORM','STOUT','STRONG','SUNKEN','SWIFT','TALL','TAUT','THICK','THIN',
  'TORN','TOXIC','TRUE','TWISTED','VEILED','VIOLET','WICKED','WIDE','WILD','WORN',
  'ZERO','AMBER','SHROUD','NIGHT','LOW','LATE','SLOW','FIXED','LOST','DEEP'
]

const NOUNS = [
  'ARCH','BANK','BASE','BEACON','BERM','BLADE','BLUFF','BOLT','BUNKER','CAIRN',
  'CAMP','CAVE','CHAIN','CLIFF','CODE','CORD','CRAG','CRATE','CREEK','CREST',
  'CROSS','DALE','DECK','DEPOT','DEN','DOOR','DRAW','DRUM','DUNE','DUST',
  'DYKE','EDGE','FANG','FERN','FIELD','FLAG','FLANK','FORD','FORK','GATE',
  'GAP','GEAR','GLEN','GRID','GROVE','GUARD','GULLY','HAVEN','HEAP','HELM',
  'HILL','HOLE','HOOK','HULL','HUB','KEEP','KNOB','KNOT','LAIR','LATCH',
  'LEDGE','LINE','LINK','LOCK','LOOP','MARK','MESA','MESH','MILL','MOAT',
  'MOOR','MOUND','MOUNT','NEST','NET','NODE','NOTCH','OAK','OUTPOST','PACK',
  'PASS','PATCH','PATH','PEAK','PEAT','PIER','PILE','PINE','PIPE','POINT',
  'POOL','PORT','PROTOCOL','RACK','RAMP','REACH','REEF','RELAY','RIDGE','RISE',
  'ROAD','ROPE','ROUTE','RUN','SCARP','SECTOR','SHAFT','SHELF','SHOAL','SHORE',
  'SIGNAL','SITE','SLAB','SLOPE','SPAN','SPIKE','SPRING','SPUR','STACK','STAKE',
  'STAND','STATION','STEP','STOCK','STORE','STRAP','SURGE','SUMP','SWALE','TANK',
  'TENT','TOLL','TRACK','TRAIL','TRAP','TUBE','UNIT','VALE','VAULT','VENT',
  'WARD','WATCH','WAVE','WELL','WIRE','YARD','ZONE','BRACE','CROWN','CACHE'
]

export function generateSlug() {
  const adj  = ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)]
  const noun = NOUNS[Math.floor(Math.random() * NOUNS.length)]
  return `${adj}-${noun}`
}
